config/routes.rb
Elearning::Application.routes.draw do |map|

  root :to => "pages#home"

  match 'watch', :to => "pages#watch"
  match 'buy', :to => "pages#buy"
	match 'shop', :to => "pages#shop"

	match 'my_account', :to => "pages#account"

  match 'about', :to => "pages#about"
  match 'contact', :to => "pages#contact"
  match 'faq', :to => "pages#faq"
  match '/logout', :to => "users#logout"
  match '/login', :to => "users#login"
  match '/signin', :to => "users#signin"
  match '/signout', :to => "users#logout"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/faq"

  resources :products
  resources :users

end

app/models/code.rb
class Code < ActiveRecord::Base

	["openssl", "digest/sha1"].each { |r| require r }

	belongs_to :product
	belongs_to :user

	before_create :generate_code

	validates :product_id, :presence => true
	validates :user_id, :presence => true
	validates :expires_at, :presence => true

  def self.not_expired
    where("expires_at > ?", Time.now)
  end

	protected
	def generate_code
		self.download_code = Digest::SHA1.hexdigest(OpenSSL::Random.random_bytes(512))
	end

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :codes

	validates :name, :presence => true, :uniqueness => true
	validates :description, :presence => true
	validates :price, :presence => true, :numericality => true, :not_zero => true
	validates :download_url, :presence => true, :uniqueness => true, :url_format => true

end

app/models/user.rb
class User < ActiveRecord::Base

	["openssl", "digest/sha1"].each { |r| require r }

	has_many :codes

	before_create :secure_password

	validates :name, :presence => true
	validates :email, :presence => true, :uniqueness => true, :email_format => true
	validates :password, :presence => true

	protected
	def secure_password
		salt = Digest::SHA1.hexdigest(OpenSSL::Random.random_bytes(512))
		encrypted_password = Digest::SHA1.hexdigest("#{self.password}--#{salt}")
		self.salt = salt
		self.password = encrypted_password
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def logged_in?
    unless session[:current_user]
      redirect_to(signin_path, :notice => 'Please sign in first')
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :logged_in?, :only => [:account]

  def home
  end

  def contact
  end

  def about
  end

  def faq
  end

	def account
		@codes = User.where("id = ?", session[:current_user].first.id).first.codes.not_expired
	end

	def shop
		@products = Product.all
	end

	def buy
		if session[:current_user]
			@code = Code.create(:user_id => session[:current_user].first.id,
											 		:product_id => params[:id],
											 		:expires_at => Time.now + 24.hours
											)
			redirect_to my_account_path
		else
		  flash[:login_error] = "Please login first"
      redirect_to signin_path
		end
	end

	def watch
	  @code = Code.where("id = ?", params[:id]).first
	  if Time.now < @code.expires_at + 1.hour
	    @product = Product.where("id = ?", @code.product.id).first
	  else
	    redirect_to my_account_path
	  end
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	["openssl", "digest/sha1"].each { |r| require r }

  before_filter :logged_in?, :except => [:signin, :login, :signout, :logout]

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def login
    @user = User.where("email = ?", params[:email])

    unless @user.empty?
      if @user.first.password == Digest::SHA1.hexdigest("#{params[:password]}--#{@user.first.salt}")
        session[:current_user] = @user
        redirect_to root_path
      else
        flash[:login_error] = "Wrong login details, try again"
        redirect_to signin_path
      end
    else
      flash[:login_error] = "User not found, try again"
      redirect_to signin_path
    end
  end

  def logout
    session[:current_user] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		true if session[:current_user]
	end

  def time_to_gmt time
    time + 1.hour
  end

end

app/helpers/pages_helper.rb
module PagesHelper

  def download_expired? time
    true if Time.now > time + 1.hour
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<footer>

  <copyright>All rights reserved to: Elearning - Web Development by: Webnasium</copyright>

  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About us", about_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "Contact us", contact_path %></li>    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag "logo.png", :alt => "Elearning App", :class => "round" %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li>
        <% if session[:current_user] %>
          <class style="color: #09c; font-weight: bold;"><%= "Logged in: #{session[:current_user].first.name}" %></class>
          <li><%= link_to '(Sign out)', logout_path %></li>
      <% else %>
        <div id="login-button"><%= link_to_function 'Sign in' %></div>
        <div id="login" style="display: none;"><%= render 'layouts/login' %></div>
      <% end %>
      </li>
      <% if logged_in? %><li><%= link_to 'My account', my_account_path %></li><% end %>
      <li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About us", about_path %></li>
			<li><%= link_to "FAQ", faq_path %></li>
			<li><%= link_to "Contact us", contact_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_login.html.erb
<%= form_tag login_path do %>
  <div class="field">
    email <class id="username" style="margin-left: 24px;"><%= text_field_tag :email %></class>
  </div>
  <div class="field">
    password <password><%= password_field_tag :password %></password>
  </div>
  <div class="actions">
    <class style="margin-left: 170px;"><%= submit_tag 'Sign in' %></class>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<menu class="round">
	<ul>
		<li><%= link_to "Shop", shop_path %></li>
	</ul>
</menu>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery_ui', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elearning</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag 'jquery',
                             'jquery_ui',
                             'application',
                             :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
	<%= render 'layouts/menu' %>
  <section class="round">
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/account.html.erb
<h4> Purchases: </h4>

<% unless @codes.empty? %>
	<ul>
		<% @codes.each do |code| %>
			<li><%= "#{code.product.name}" %> -
			    (<%= time_to_gmt(code.expires_at).strftime("expires: %a %d/%m/%y at %H:%M") %>) -
			    <% unless download_expired? code.expires_at %>
            <%= link_to 'Watch lesson', watch_path(:id => code.id) %>
			    <% end %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/shop.html.erb
<% unless @products.empty? %>
	<h4>Products: </h4>
	<% @products.each do |product| %>
		<%= product.name %> | <%= link_to 'Buy', buy_url(:id => product.id) %><br />
	<% end %>
<% end %>

app/views/pages/watch.html.erb
<script>
  jQuery(function() {

    jQuery(document).click(function(){
      jQuery('#player').dialog("close");
    });

    jQuery('#player').dialog({
      title: 'Lesson player: (press Esc key to close)',
			resizable: false,
			autoOpen: true,
			show: 'blind',
			height: 430,
			width: 507,
			modal: true,
			draggable: false,
			close: function() { window.location.replace('/my_account'); },
			open: function() { jQuery(".ui-dialog-titlebar-close").hide(); }
    });
  });
</script>

<div id="player">
  <object width="480" height="385"><param name="movie" value="<%= @product.download_url %>&amp;hl=en_GB&amp;fs=1"></param>
    <param name="allowFullScreen" value="true"></param>
    <param name="allowscriptaccess" value="always"></param>
    <embed src="<%= @product.download_url %>&amp;hl=en_GB&amp;fs=1?color1=0x006699&amp;color2=0x54abd6&amp;border=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="385"></embed>
  </object>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :download_url %><br />
    <%= f.text_field :download_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Download url</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.download_url %></td>
    <td><%= number_to_currency product.price, :unit => '£' %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Download url:</b>
  <%= @product.download_url %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price, :unit => '£' %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password.gsub(/./, '*') %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password.gsub(/./, '*') %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signin.html.erb
<login_page>
<% if flash[:login_error] %><div class="login_page_error"><%= flash[:login_error] %></div><% end %>
<%= form_tag login_path do %>
  <div class="field">
    Enter your login details:<br /><br />
    email: <br
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    password: <br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag 'Sign in' %>
  </div>
<% end %>
</login_page>